export const MATERIALS_DISBURSEMENT_PERMISSIONS = {
  VIEW: 'MATERIALS_DISBURSEMENT_VIEW',
  CREATE: 'MATERIALS_DISBURSEMENT_CREATE',
  UPDATE: 'MATERIALS_DISBURSEMENT_UPDATE',
  DELETE: 'MATERIALS_DISBURSEMENT_DELETE',
  CONFIRM: 'MATERIALS_DISBURSEMENT_CONFIRM',
  CANCEL: 'MATERIALS_DISBURSEMENT_CANCEL',
} as const;
