import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateDepartmentPermissions1700000000003
  implements MigrationInterface
{
  name = 'CreateDepartmentPermissions1700000000003';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS iam.department_permissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        permission_id BIGINT NOT NULL,
        department_id BIGINT NOT NULL,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT uq_department_permissions_permission_department
          UNIQUE (permission_id, department_id),
        CONSTRAINT fk_department_permissions_permission
          FOREIGN KEY (permission_id)
          REFERENCES iam.permissions(id)
          ON DELETE CASCADE,
        CONSTRAINT fk_department_permissions_department
          FOREIGN KEY (department_id)
          REFERENCES iam.departments(id)
          ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_department_permissions_permission_id
      ON iam.department_permissions(permission_id)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_department_permissions_department_id
      ON iam.department_permissions(department_id)
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE IF EXISTS iam.department_permissions
    `);
  }
}
