import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPackingQuantityToMaterial1786197666074 implements MigrationInterface {
    name = 'AddPackingQuantityToMaterial1786197666074'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "master"."materials" DROP CONSTRAINT "materials_unit_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "master"."materials" DROP CONSTRAINT "materials_delivery_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "master"."materials" DROP CONSTRAINT "materials_model_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "master"."materials" DROP CONSTRAINT "materials_loading_point_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" DROP CONSTRAINT "supplier_materials_material_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" DROP CONSTRAINT "supplier_materials_supplier_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "master"."categories" DROP CONSTRAINT "categories_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "master"."organizations" DROP CONSTRAINT "organizations_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_attachments" DROP CONSTRAINT "fk_goods_receipt_attachments_receipt"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" DROP CONSTRAINT "fk_goods_receipts_organization"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" DROP CONSTRAINT "fk_goods_receipts_supplier"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "fk_goods_receipt_items_receipt"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "fk_goods_receipt_items_material"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "fk_goods_receipt_items_unit"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "fk_goods_receipt_items_reject_reason"`);
        await queryRunner.query(`ALTER TABLE "inventory"."document_counters" DROP CONSTRAINT "fk_document_counters_organization"`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" DROP CONSTRAINT "menus_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" DROP CONSTRAINT "permissions_menu_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" DROP CONSTRAINT "permissions_action_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" DROP CONSTRAINT "fk_department_permissions_permission"`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" DROP CONSTRAINT "fk_department_permissions_department"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" DROP CONSTRAINT "user_department_roles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" DROP CONSTRAINT "user_department_roles_department_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" DROP CONSTRAINT "user_department_roles_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" DROP CONSTRAINT "role_actions_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" DROP CONSTRAINT "role_actions_action_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" DROP CONSTRAINT "user_department_permissions_user_department_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" DROP CONSTRAINT "user_department_permissions_permission_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" DROP CONSTRAINT "auth_sessions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" DROP CONSTRAINT "auth_sessions_active_user_department_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."audit_logs" DROP CONSTRAINT "audit_logs_actor_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "iam"."audit_logs" DROP CONSTRAINT "audit_logs_department_id_fkey"`);
        await queryRunner.query(`DROP INDEX "master"."idx_materials_unit_id"`);
        await queryRunner.query(`DROP INDEX "master"."idx_materials_delivery_type_id"`);
        await queryRunner.query(`DROP INDEX "master"."idx_materials_model_id"`);
        await queryRunner.query(`DROP INDEX "master"."idx_materials_loading_point_id"`);
        await queryRunner.query(`DROP INDEX "master"."idx_supplier_materials_material_id"`);
        await queryRunner.query(`DROP INDEX "master"."idx_supplier_materials_supplier_id"`);
        await queryRunner.query(`DROP INDEX "master"."idx_status_items_module"`);
        await queryRunner.query(`DROP INDEX "master"."idx_categories_parent_id"`);
        await queryRunner.query(`DROP INDEX "master"."idx_organizations_parent_id"`);
        await queryRunner.query(`DROP INDEX "inventory"."idx_goods_receipt_attachments_receipt_id"`);
        await queryRunner.query(`DROP INDEX "inventory"."uq_goods_receipts_receipt_no"`);
        await queryRunner.query(`DROP INDEX "inventory"."uq_goods_receipts_supplier_doc_no"`);
        await queryRunner.query(`DROP INDEX "inventory"."idx_goods_receipts_supplier_id"`);
        await queryRunner.query(`DROP INDEX "inventory"."idx_goods_receipts_organization_id"`);
        await queryRunner.query(`DROP INDEX "inventory"."idx_goods_receipts_receipt_date"`);
        await queryRunner.query(`DROP INDEX "inventory"."idx_goods_receipts_status"`);
        await queryRunner.query(`DROP INDEX "inventory"."uq_goods_receipt_items_material_lot"`);
        await queryRunner.query(`DROP INDEX "inventory"."idx_goods_receipt_items_receipt_id"`);
        await queryRunner.query(`DROP INDEX "inventory"."idx_goods_receipt_items_material_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_department_permissions_permission_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_department_permissions_department_id"`);
        await queryRunner.query(`DROP INDEX "iam"."uq_user_department_roles_user_system_role"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_user_department_roles_user_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_user_department_roles_department_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_user_department_roles_role_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_user_department_permissions_user_department_role_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_user_department_permissions_permission_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_auth_sessions_user_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_auth_sessions_active_user_department_role_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_audit_logs_actor_user_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_audit_logs_department_id"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_audit_logs_action"`);
        await queryRunner.query(`DROP INDEX "iam"."idx_audit_logs_created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_attachments" DROP CONSTRAINT "chk_goods_receipt_attachments_doc_type"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_attachments" DROP CONSTRAINT "chk_goods_receipt_attachments_file_size"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" DROP CONSTRAINT "chk_goods_receipts_status"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" DROP CONSTRAINT "chk_goods_receipts_posted_fields"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" DROP CONSTRAINT "chk_goods_receipts_cancelled_fields"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "chk_goods_receipt_items_qty_sign"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "chk_goods_receipt_items_qty_total"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "chk_goods_receipt_items_qty_not_zero"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "chk_goods_receipt_items_reject_reason"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "chk_goods_receipt_items_price"`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" DROP CONSTRAINT "menus_menu_type_check"`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" DROP CONSTRAINT "roles_scope_type_check"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" DROP CONSTRAINT "user_department_permissions_effect_check"`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" DROP CONSTRAINT "supplier_materials_material_id_supplier_id_key"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "uq_goods_receipt_items_line"`);
        await queryRunner.query(`ALTER TABLE "inventory"."document_counters" DROP CONSTRAINT "uq_document_counters_scope"`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" DROP CONSTRAINT "permissions_menu_id_action_id_key"`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" DROP CONSTRAINT "uq_department_permissions_permission_department"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" DROP CONSTRAINT "uq_user_department_roles_user_department_role"`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" DROP CONSTRAINT "role_actions_role_id_action_id_key"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" DROP COLUMN "po_no"`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ADD "packing_quantity" integer`);
        await queryRunner.query(`ALTER TABLE "master"."units" DROP CONSTRAINT "units_code_key"`);
        await queryRunner.query(`ALTER TABLE "master"."units" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."units" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."delivery_types" DROP CONSTRAINT "delivery_types_code_key"`);
        await queryRunner.query(`ALTER TABLE "master"."delivery_types" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."delivery_types" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."loading_points" DROP CONSTRAINT "loading_points_code_key"`);
        await queryRunner.query(`ALTER TABLE "master"."loading_points" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."loading_points" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."material_models" DROP CONSTRAINT "material_models_code_key"`);
        await queryRunner.query(`ALTER TABLE "master"."material_models" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."material_models" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."materials" DROP CONSTRAINT "materials_code_key"`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."suppliers" DROP CONSTRAINT "suppliers_code_key"`);
        await queryRunner.query(`ALTER TABLE "master"."suppliers" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."suppliers" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."status_items" DROP CONSTRAINT "status_items_code_key"`);
        await queryRunner.query(`ALTER TABLE "master"."status_items" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."status_items" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."reject_reasons" DROP CONSTRAINT "reject_reasons_code_key"`);
        await queryRunner.query(`ALTER TABLE "master"."reject_reasons" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."reject_reasons" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."categories" DROP CONSTRAINT "categories_code_key"`);
        await queryRunner.query(`ALTER TABLE "master"."categories" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."categories" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."organizations" DROP CONSTRAINT "organizations_code_key"`);
        await queryRunner.query(`ALTER TABLE "master"."organizations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "master"."organizations" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_attachments" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory"."document_counters" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory"."document_counters" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "is_locked" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "failed_login_attempts" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "permission_version" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" DROP COLUMN "menu_type"`);
        await queryRunner.query(`CREATE TYPE "iam"."menus_menu_type_enum" AS ENUM('MAIN', 'SUB')`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ADD "menu_type" "iam"."menus_menu_type_enum" NOT NULL DEFAULT 'MAIN'`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "is_visible" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "is_system" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."departments" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."departments" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."departments" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."departments" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."departments" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" DROP COLUMN "scope_type"`);
        await queryRunner.query(`CREATE TYPE "iam"."roles_scope_type_enum" AS ENUM('SYSTEM', 'DEPARTMENT')`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ADD "scope_type" "iam"."roles_scope_type_enum" NOT NULL DEFAULT 'DEPARTMENT'`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "is_system" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "iam"."audit_logs" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."audit_logs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_47635c1ab22d02fc3ebae3608b" ON "master"."units" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ebaf4d3ad7cff388ff07b23951" ON "master"."delivery_types" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f6c516b7ef42ea49045cfae7b8" ON "master"."loading_points" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bf9be63a46e7aec558f69f1139" ON "master"."material_models" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_67bf324047a2d89c121f74dd40" ON "master"."materials" ("unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_161a69c9378e3583db846d657a" ON "master"."materials" ("delivery_type_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_daef65ef45cd7d585509f0c110" ON "master"."materials" ("model_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e25db71f0c521d7ce564c8d711" ON "master"."materials" ("loading_point_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5f59d61b51ffcb1db994286221" ON "master"."materials" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ac6158d031a98174dcd3f9c35" ON "master"."supplier_materials" ("material_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0a9fae368f751cc36f833040d" ON "master"."supplier_materials" ("supplier_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d03686be00485c98087c2093d6" ON "master"."supplier_materials" ("material_id", "supplier_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6f01a03dcb1aa33822e19534cd" ON "master"."suppliers" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0013b1a964d4f405d3c447239d" ON "master"."status_items" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0cd3a40c239290a99453a68c7f" ON "master"."reject_reasons" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_77d7eff8a7aaa05457a12b8007" ON "master"."categories" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7e27c3b62c681fbe3e2322535f" ON "master"."organizations" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_bfea17cc623dc516a7c1612610" ON "inventory"."goods_receipt_attachments" ("goods_receipt_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7dd02777a589d5e2d1e75a92ba" ON "inventory"."goods_receipts" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1cc80e6e1bd6c9a07decb9560f" ON "inventory"."goods_receipts" ("supplier_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_536cbd78047fc1325d999b85f9" ON "inventory"."goods_receipts" ("receipt_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_85cf4c20aa82287f7435974383" ON "inventory"."goods_receipts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e6b8fd10202a479cc40d38b3e" ON "inventory"."goods_receipt_items" ("goods_receipt_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a31248b93b8bc92b698ff9d283" ON "inventory"."goods_receipt_items" ("material_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c69e69ba0473d937f0b1f0aef6" ON "inventory"."goods_receipt_items" ("goods_receipt_id", "line_no") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9cef266319ccb61a0e47f54b1a" ON "inventory"."document_counters" ("organization_id", "doc_type", "period") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "iam"."users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_65cbf5fcb331619593ee334c7c" ON "iam"."users" ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_00ccc1ed4e9fc23bc124626935" ON "iam"."menus" ("parent_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9b9626d392ff967d6715178a3e" ON "iam"."menus" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6a06e2b9e1a744af989693a222" ON "iam"."actions" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9bcaf1da5095642dc631ffbab" ON "iam"."permissions" ("menu_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b260ff500cf388b8c01569a97e" ON "iam"."permissions" ("action_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8dad765629e83229da6feda1c1" ON "iam"."permissions" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_39e312446f4735d5bda8497ed1" ON "iam"."department_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a604945ba103f0e74f996cdc3" ON "iam"."department_permissions" ("department_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_251eca408083656bd32934072f" ON "iam"."department_permissions" ("permission_id", "department_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_91fddbe23e927e1e525c152baa" ON "iam"."departments" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f6d54f95c31b73fb1bdd8e91d0" ON "iam"."roles" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a665b97d3510d06894061a8db" ON "iam"."user_department_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4090dad03cf5f43222f2442a3a" ON "iam"."user_department_roles" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d84eaa384af8833c7137b93acc" ON "iam"."user_department_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ed4344d4ad234b70b11e3014e" ON "iam"."role_actions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_44d5d313574bc10682b6700423" ON "iam"."role_actions" ("action_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_368e7cd197ee6f5792941ca5a7" ON "iam"."user_department_permissions" ("user_department_role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d4ae73c5e08b12f9a25c8c6fa" ON "iam"."user_department_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_50ccaa6440288a06f0ba693ccc" ON "iam"."auth_sessions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6c31b08b7869c523f36047962" ON "iam"."auth_sessions" ("active_user_department_role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f160d97a931844109de9d04228" ON "iam"."audit_logs" ("actor_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_53e3762649c716bff27b45b884" ON "iam"."audit_logs" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "iam"."audit_logs" ("action") `);
        await queryRunner.query(`ALTER TABLE "master"."materials" ADD CONSTRAINT "FK_67bf324047a2d89c121f74dd401" FOREIGN KEY ("unit_id") REFERENCES "master"."units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ADD CONSTRAINT "FK_161a69c9378e3583db846d657a5" FOREIGN KEY ("delivery_type_id") REFERENCES "master"."delivery_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ADD CONSTRAINT "FK_daef65ef45cd7d585509f0c1102" FOREIGN KEY ("model_id") REFERENCES "master"."material_models"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ADD CONSTRAINT "FK_e25db71f0c521d7ce564c8d7117" FOREIGN KEY ("loading_point_id") REFERENCES "master"."loading_points"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" ADD CONSTRAINT "FK_1ac6158d031a98174dcd3f9c35d" FOREIGN KEY ("material_id") REFERENCES "master"."materials"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" ADD CONSTRAINT "FK_d0a9fae368f751cc36f833040de" FOREIGN KEY ("supplier_id") REFERENCES "master"."suppliers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_attachments" ADD CONSTRAINT "FK_bfea17cc623dc516a7c16126100" FOREIGN KEY ("goods_receipt_id") REFERENCES "inventory"."goods_receipts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ADD CONSTRAINT "FK_7dd02777a589d5e2d1e75a92ba7" FOREIGN KEY ("organization_id") REFERENCES "master"."organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ADD CONSTRAINT "FK_1cc80e6e1bd6c9a07decb9560fe" FOREIGN KEY ("supplier_id") REFERENCES "master"."suppliers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "FK_6e6b8fd10202a479cc40d38b3ef" FOREIGN KEY ("goods_receipt_id") REFERENCES "inventory"."goods_receipts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "FK_a31248b93b8bc92b698ff9d2839" FOREIGN KEY ("material_id") REFERENCES "master"."materials"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "FK_d7710e4cf2625b0e494acad531e" FOREIGN KEY ("unit_id") REFERENCES "master"."units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "FK_3049c2f6e2d597ebde0adcaa502" FOREIGN KEY ("reject_reason_id") REFERENCES "master"."reject_reasons"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ADD CONSTRAINT "FK_00ccc1ed4e9fc23bc1246269359" FOREIGN KEY ("parent_id") REFERENCES "iam"."menus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ADD CONSTRAINT "FK_b9bcaf1da5095642dc631ffbabf" FOREIGN KEY ("menu_id") REFERENCES "iam"."menus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ADD CONSTRAINT "FK_b260ff500cf388b8c01569a97e1" FOREIGN KEY ("action_id") REFERENCES "iam"."actions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" ADD CONSTRAINT "FK_39e312446f4735d5bda8497ed13" FOREIGN KEY ("permission_id") REFERENCES "iam"."permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" ADD CONSTRAINT "FK_6a604945ba103f0e74f996cdc3b" FOREIGN KEY ("department_id") REFERENCES "iam"."departments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ADD CONSTRAINT "FK_9a665b97d3510d06894061a8db6" FOREIGN KEY ("user_id") REFERENCES "iam"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ADD CONSTRAINT "FK_4090dad03cf5f43222f2442a3a5" FOREIGN KEY ("department_id") REFERENCES "iam"."departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ADD CONSTRAINT "FK_d84eaa384af8833c7137b93acc0" FOREIGN KEY ("role_id") REFERENCES "iam"."roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ADD CONSTRAINT "FK_2ed4344d4ad234b70b11e3014ed" FOREIGN KEY ("role_id") REFERENCES "iam"."roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ADD CONSTRAINT "FK_44d5d313574bc10682b67004239" FOREIGN KEY ("action_id") REFERENCES "iam"."actions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ADD CONSTRAINT "FK_368e7cd197ee6f5792941ca5a74" FOREIGN KEY ("user_department_role_id") REFERENCES "iam"."user_department_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ADD CONSTRAINT "FK_1d4ae73c5e08b12f9a25c8c6fa2" FOREIGN KEY ("permission_id") REFERENCES "iam"."permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ADD CONSTRAINT "FK_50ccaa6440288a06f0ba693ccc6" FOREIGN KEY ("user_id") REFERENCES "iam"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ADD CONSTRAINT "FK_d6c31b08b7869c523f36047962d" FOREIGN KEY ("active_user_department_role_id") REFERENCES "iam"."user_department_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."audit_logs" ADD CONSTRAINT "FK_f160d97a931844109de9d04228f" FOREIGN KEY ("actor_user_id") REFERENCES "iam"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "iam"."audit_logs" DROP CONSTRAINT "FK_f160d97a931844109de9d04228f"`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" DROP CONSTRAINT "FK_d6c31b08b7869c523f36047962d"`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" DROP CONSTRAINT "FK_50ccaa6440288a06f0ba693ccc6"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" DROP CONSTRAINT "FK_1d4ae73c5e08b12f9a25c8c6fa2"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" DROP CONSTRAINT "FK_368e7cd197ee6f5792941ca5a74"`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" DROP CONSTRAINT "FK_44d5d313574bc10682b67004239"`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" DROP CONSTRAINT "FK_2ed4344d4ad234b70b11e3014ed"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" DROP CONSTRAINT "FK_d84eaa384af8833c7137b93acc0"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" DROP CONSTRAINT "FK_4090dad03cf5f43222f2442a3a5"`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" DROP CONSTRAINT "FK_9a665b97d3510d06894061a8db6"`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" DROP CONSTRAINT "FK_6a604945ba103f0e74f996cdc3b"`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" DROP CONSTRAINT "FK_39e312446f4735d5bda8497ed13"`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" DROP CONSTRAINT "FK_b260ff500cf388b8c01569a97e1"`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" DROP CONSTRAINT "FK_b9bcaf1da5095642dc631ffbabf"`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" DROP CONSTRAINT "FK_00ccc1ed4e9fc23bc1246269359"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "FK_3049c2f6e2d597ebde0adcaa502"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "FK_d7710e4cf2625b0e494acad531e"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "FK_a31248b93b8bc92b698ff9d2839"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" DROP CONSTRAINT "FK_6e6b8fd10202a479cc40d38b3ef"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" DROP CONSTRAINT "FK_1cc80e6e1bd6c9a07decb9560fe"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" DROP CONSTRAINT "FK_7dd02777a589d5e2d1e75a92ba7"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_attachments" DROP CONSTRAINT "FK_bfea17cc623dc516a7c16126100"`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" DROP CONSTRAINT "FK_d0a9fae368f751cc36f833040de"`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" DROP CONSTRAINT "FK_1ac6158d031a98174dcd3f9c35d"`);
        await queryRunner.query(`ALTER TABLE "master"."materials" DROP CONSTRAINT "FK_e25db71f0c521d7ce564c8d7117"`);
        await queryRunner.query(`ALTER TABLE "master"."materials" DROP CONSTRAINT "FK_daef65ef45cd7d585509f0c1102"`);
        await queryRunner.query(`ALTER TABLE "master"."materials" DROP CONSTRAINT "FK_161a69c9378e3583db846d657a5"`);
        await queryRunner.query(`ALTER TABLE "master"."materials" DROP CONSTRAINT "FK_67bf324047a2d89c121f74dd401"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_53e3762649c716bff27b45b884"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_f160d97a931844109de9d04228"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_d6c31b08b7869c523f36047962"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_50ccaa6440288a06f0ba693ccc"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_1d4ae73c5e08b12f9a25c8c6fa"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_368e7cd197ee6f5792941ca5a7"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_44d5d313574bc10682b6700423"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_2ed4344d4ad234b70b11e3014e"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_d84eaa384af8833c7137b93acc"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_4090dad03cf5f43222f2442a3a"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_9a665b97d3510d06894061a8db"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_f6d54f95c31b73fb1bdd8e91d0"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_91fddbe23e927e1e525c152baa"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_251eca408083656bd32934072f"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_6a604945ba103f0e74f996cdc3"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_39e312446f4735d5bda8497ed1"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_8dad765629e83229da6feda1c1"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_b260ff500cf388b8c01569a97e"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_b9bcaf1da5095642dc631ffbab"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_6a06e2b9e1a744af989693a222"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_9b9626d392ff967d6715178a3e"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_00ccc1ed4e9fc23bc124626935"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_65cbf5fcb331619593ee334c7c"`);
        await queryRunner.query(`DROP INDEX "iam"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP INDEX "inventory"."IDX_9cef266319ccb61a0e47f54b1a"`);
        await queryRunner.query(`DROP INDEX "inventory"."IDX_c69e69ba0473d937f0b1f0aef6"`);
        await queryRunner.query(`DROP INDEX "inventory"."IDX_a31248b93b8bc92b698ff9d283"`);
        await queryRunner.query(`DROP INDEX "inventory"."IDX_6e6b8fd10202a479cc40d38b3e"`);
        await queryRunner.query(`DROP INDEX "inventory"."IDX_85cf4c20aa82287f7435974383"`);
        await queryRunner.query(`DROP INDEX "inventory"."IDX_536cbd78047fc1325d999b85f9"`);
        await queryRunner.query(`DROP INDEX "inventory"."IDX_1cc80e6e1bd6c9a07decb9560f"`);
        await queryRunner.query(`DROP INDEX "inventory"."IDX_7dd02777a589d5e2d1e75a92ba"`);
        await queryRunner.query(`DROP INDEX "inventory"."IDX_bfea17cc623dc516a7c1612610"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_7e27c3b62c681fbe3e2322535f"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_77d7eff8a7aaa05457a12b8007"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_0cd3a40c239290a99453a68c7f"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_0013b1a964d4f405d3c447239d"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_6f01a03dcb1aa33822e19534cd"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_d03686be00485c98087c2093d6"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_d0a9fae368f751cc36f833040d"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_1ac6158d031a98174dcd3f9c35"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_5f59d61b51ffcb1db994286221"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_e25db71f0c521d7ce564c8d711"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_daef65ef45cd7d585509f0c110"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_161a69c9378e3583db846d657a"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_67bf324047a2d89c121f74dd40"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_bf9be63a46e7aec558f69f1139"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_f6c516b7ef42ea49045cfae7b8"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_ebaf4d3ad7cff388ff07b23951"`);
        await queryRunner.query(`DROP INDEX "master"."IDX_47635c1ab22d02fc3ebae3608b"`);
        await queryRunner.query(`ALTER TABLE "iam"."audit_logs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."audit_logs" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ALTER COLUMN "is_system" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" DROP COLUMN "scope_type"`);
        await queryRunner.query(`DROP TYPE "iam"."roles_scope_type_enum"`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ADD "scope_type" character varying(20) DEFAULT 'DEPARTMENT'`);
        await queryRunner.query(`ALTER TABLE "iam"."departments" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."departments" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."departments" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."departments" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."departments" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "is_system" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."actions" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "is_visible" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" DROP COLUMN "menu_type"`);
        await queryRunner.query(`DROP TYPE "iam"."menus_menu_type_enum"`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ADD "menu_type" character varying(10) DEFAULT 'MAIN'`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "permission_version" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "failed_login_attempts" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "is_locked" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam"."users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory"."document_counters" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory"."document_counters" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_attachments" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."organizations" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."organizations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."organizations" ADD CONSTRAINT "organizations_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."categories" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."categories" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."categories" ADD CONSTRAINT "categories_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."reject_reasons" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."reject_reasons" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."reject_reasons" ADD CONSTRAINT "reject_reasons_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."status_items" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."status_items" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."status_items" ADD CONSTRAINT "status_items_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."suppliers" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."suppliers" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."suppliers" ADD CONSTRAINT "suppliers_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ADD CONSTRAINT "materials_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."material_models" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."material_models" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."material_models" ADD CONSTRAINT "material_models_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."loading_points" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."loading_points" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."loading_points" ADD CONSTRAINT "loading_points_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."delivery_types" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."delivery_types" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."delivery_types" ADD CONSTRAINT "delivery_types_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."units" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."units" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "master"."units" ADD CONSTRAINT "units_code_key" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "master"."materials" DROP COLUMN "packing_quantity"`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ADD "po_no" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ADD CONSTRAINT "role_actions_role_id_action_id_key" UNIQUE ("role_id", "action_id")`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ADD CONSTRAINT "uq_user_department_roles_user_department_role" UNIQUE ("user_id", "department_id", "role_id")`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" ADD CONSTRAINT "uq_department_permissions_permission_department" UNIQUE ("permission_id", "department_id")`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ADD CONSTRAINT "permissions_menu_id_action_id_key" UNIQUE ("menu_id", "action_id")`);
        await queryRunner.query(`ALTER TABLE "inventory"."document_counters" ADD CONSTRAINT "uq_document_counters_scope" UNIQUE ("organization_id", "doc_type", "period")`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "uq_goods_receipt_items_line" UNIQUE ("goods_receipt_id", "line_no")`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" ADD CONSTRAINT "supplier_materials_material_id_supplier_id_key" UNIQUE ("material_id", "supplier_id")`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ADD CONSTRAINT "user_department_permissions_effect_check" CHECK (((effect)::text = ANY ((ARRAY['ALLOW'::character varying, 'DENY'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "iam"."roles" ADD CONSTRAINT "roles_scope_type_check" CHECK (((scope_type)::text = ANY ((ARRAY['SYSTEM'::character varying, 'DEPARTMENT'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ADD CONSTRAINT "menus_menu_type_check" CHECK (((menu_type)::text = ANY ((ARRAY['MAIN'::character varying, 'SUB'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "chk_goods_receipt_items_price" CHECK ((((unit_price IS NULL) OR (unit_price >= (0)::numeric)) AND ((line_amount IS NULL) OR (line_amount >= (0)::numeric))))`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "chk_goods_receipt_items_reject_reason" CHECK (((qty_rejected = (0)::numeric) OR (reject_reason_id IS NOT NULL)))`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "chk_goods_receipt_items_qty_not_zero" CHECK (((qty_received > (0)::numeric) OR (qty_rejected > (0)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "chk_goods_receipt_items_qty_total" CHECK (((qty_received + qty_rejected) <= qty_delivered))`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "chk_goods_receipt_items_qty_sign" CHECK (((qty_delivered >= (0)::numeric) AND (qty_received >= (0)::numeric) AND (qty_rejected >= (0)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ADD CONSTRAINT "chk_goods_receipts_cancelled_fields" CHECK ((((status)::text <> 'cancelled'::text) OR ((cancelled_by IS NOT NULL) AND (cancelled_at IS NOT NULL) AND (cancel_reason IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ADD CONSTRAINT "chk_goods_receipts_posted_fields" CHECK (((((status)::text <> 'posted'::text) AND ((status)::text <> 'cancelled'::text)) OR ((receipt_no IS NOT NULL) AND (posted_by IS NOT NULL) AND (posted_at IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ADD CONSTRAINT "chk_goods_receipts_status" CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'posted'::character varying, 'cancelled'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_attachments" ADD CONSTRAINT "chk_goods_receipt_attachments_file_size" CHECK ((file_size > 0))`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_attachments" ADD CONSTRAINT "chk_goods_receipt_attachments_doc_type" CHECK (((doc_type)::text = ANY ((ARRAY['DELIVERY_NOTE'::character varying, 'TAX_INVOICE'::character varying, 'PHOTO'::character varying, 'OTHER'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_created_at" ON "iam"."audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_action" ON "iam"."audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_department_id" ON "iam"."audit_logs" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_actor_user_id" ON "iam"."audit_logs" ("actor_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_sessions_active_user_department_role_id" ON "iam"."auth_sessions" ("active_user_department_role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_sessions_user_id" ON "iam"."auth_sessions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_department_permissions_permission_id" ON "iam"."user_department_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_department_permissions_user_department_role_id" ON "iam"."user_department_permissions" ("user_department_role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_department_roles_role_id" ON "iam"."user_department_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_department_roles_department_id" ON "iam"."user_department_roles" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_department_roles_user_id" ON "iam"."user_department_roles" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_user_department_roles_user_system_role" ON "iam"."user_department_roles" ("role_id", "user_id") WHERE (department_id IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_department_permissions_department_id" ON "iam"."department_permissions" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "idx_department_permissions_permission_id" ON "iam"."department_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "idx_goods_receipt_items_material_id" ON "inventory"."goods_receipt_items" ("material_id") `);
        await queryRunner.query(`CREATE INDEX "idx_goods_receipt_items_receipt_id" ON "inventory"."goods_receipt_items" ("goods_receipt_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_goods_receipt_items_material_lot" ON "inventory"."goods_receipt_items" ("goods_receipt_id", "material_id") `);
        await queryRunner.query(`CREATE INDEX "idx_goods_receipts_status" ON "inventory"."goods_receipts" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_goods_receipts_receipt_date" ON "inventory"."goods_receipts" ("receipt_date") `);
        await queryRunner.query(`CREATE INDEX "idx_goods_receipts_organization_id" ON "inventory"."goods_receipts" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_goods_receipts_supplier_id" ON "inventory"."goods_receipts" ("supplier_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_goods_receipts_supplier_doc_no" ON "inventory"."goods_receipts" ("supplier_doc_no", "supplier_id") WHERE ((no_supplier_document = false) AND (supplier_doc_no IS NOT NULL) AND ((status)::text <> 'cancelled'::text))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_goods_receipts_receipt_no" ON "inventory"."goods_receipts" ("organization_id", "receipt_no") WHERE (receipt_no IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_goods_receipt_attachments_receipt_id" ON "inventory"."goods_receipt_attachments" ("goods_receipt_id") `);
        await queryRunner.query(`CREATE INDEX "idx_organizations_parent_id" ON "master"."organizations" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "idx_categories_parent_id" ON "master"."categories" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "idx_status_items_module" ON "master"."status_items" ("module") `);
        await queryRunner.query(`CREATE INDEX "idx_supplier_materials_supplier_id" ON "master"."supplier_materials" ("supplier_id") `);
        await queryRunner.query(`CREATE INDEX "idx_supplier_materials_material_id" ON "master"."supplier_materials" ("material_id") `);
        await queryRunner.query(`CREATE INDEX "idx_materials_loading_point_id" ON "master"."materials" ("loading_point_id") `);
        await queryRunner.query(`CREATE INDEX "idx_materials_model_id" ON "master"."materials" ("model_id") `);
        await queryRunner.query(`CREATE INDEX "idx_materials_delivery_type_id" ON "master"."materials" ("delivery_type_id") `);
        await queryRunner.query(`CREATE INDEX "idx_materials_unit_id" ON "master"."materials" ("unit_id") `);
        await queryRunner.query(`ALTER TABLE "iam"."audit_logs" ADD CONSTRAINT "audit_logs_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "iam"."departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."audit_logs" ADD CONSTRAINT "audit_logs_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "iam"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ADD CONSTRAINT "auth_sessions_active_user_department_role_id_fkey" FOREIGN KEY ("active_user_department_role_id") REFERENCES "iam"."user_department_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."auth_sessions" ADD CONSTRAINT "auth_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "iam"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ADD CONSTRAINT "user_department_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "iam"."permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_permissions" ADD CONSTRAINT "user_department_permissions_user_department_role_id_fkey" FOREIGN KEY ("user_department_role_id") REFERENCES "iam"."user_department_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ADD CONSTRAINT "role_actions_action_id_fkey" FOREIGN KEY ("action_id") REFERENCES "iam"."actions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."role_actions" ADD CONSTRAINT "role_actions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "iam"."roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ADD CONSTRAINT "user_department_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "iam"."roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ADD CONSTRAINT "user_department_roles_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "iam"."departments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."user_department_roles" ADD CONSTRAINT "user_department_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "iam"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" ADD CONSTRAINT "fk_department_permissions_department" FOREIGN KEY ("department_id") REFERENCES "iam"."departments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."department_permissions" ADD CONSTRAINT "fk_department_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "iam"."permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ADD CONSTRAINT "permissions_action_id_fkey" FOREIGN KEY ("action_id") REFERENCES "iam"."actions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."permissions" ADD CONSTRAINT "permissions_menu_id_fkey" FOREIGN KEY ("menu_id") REFERENCES "iam"."menus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iam"."menus" ADD CONSTRAINT "menus_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "iam"."menus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."document_counters" ADD CONSTRAINT "fk_document_counters_organization" FOREIGN KEY ("organization_id") REFERENCES "master"."organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "fk_goods_receipt_items_reject_reason" FOREIGN KEY ("reject_reason_id") REFERENCES "master"."reject_reasons"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "fk_goods_receipt_items_unit" FOREIGN KEY ("unit_id") REFERENCES "master"."units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "fk_goods_receipt_items_material" FOREIGN KEY ("material_id") REFERENCES "master"."materials"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_items" ADD CONSTRAINT "fk_goods_receipt_items_receipt" FOREIGN KEY ("goods_receipt_id") REFERENCES "inventory"."goods_receipts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ADD CONSTRAINT "fk_goods_receipts_supplier" FOREIGN KEY ("supplier_id") REFERENCES "master"."suppliers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipts" ADD CONSTRAINT "fk_goods_receipts_organization" FOREIGN KEY ("organization_id") REFERENCES "master"."organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory"."goods_receipt_attachments" ADD CONSTRAINT "fk_goods_receipt_attachments_receipt" FOREIGN KEY ("goods_receipt_id") REFERENCES "inventory"."goods_receipts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."organizations" ADD CONSTRAINT "organizations_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "master"."organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."categories" ADD CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "master"."categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" ADD CONSTRAINT "supplier_materials_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "master"."suppliers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."supplier_materials" ADD CONSTRAINT "supplier_materials_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "master"."materials"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ADD CONSTRAINT "materials_loading_point_id_fkey" FOREIGN KEY ("loading_point_id") REFERENCES "master"."loading_points"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ADD CONSTRAINT "materials_model_id_fkey" FOREIGN KEY ("model_id") REFERENCES "master"."material_models"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ADD CONSTRAINT "materials_delivery_type_id_fkey" FOREIGN KEY ("delivery_type_id") REFERENCES "master"."delivery_types"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "master"."materials" ADD CONSTRAINT "materials_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "master"."units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
