--
-- PostgreSQL database dump
--

\restrict 6jY4oxSyTm4hWK3iPtKbLJhZJdWcLyzhh7SuowyqDZA85b9NqpKs2DqyVe8eQkj

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: iam; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA iam;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actions; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.actions (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    name_th character varying(50) NOT NULL,
    name_en character varying(50) NOT NULL,
    description text,
    sort_order integer DEFAULT 0,
    is_system boolean DEFAULT true,
    is_active boolean DEFAULT true,
    created_by bigint,
    updated_by bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: actions_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.actions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.audit_logs (
    id bigint NOT NULL,
    actor_user_id bigint,
    department_id bigint,
    action character varying(50) NOT NULL,
    target_type character varying(50),
    target_id bigint,
    before_data jsonb,
    after_data jsonb,
    ip_address character varying(45),
    user_agent text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    trace_id character varying(40),
    request_id character varying(80),
    reason text
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.audit_logs ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_sessions; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.auth_sessions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    active_user_department_role_id bigint,
    refresh_token_hash character varying(255) NOT NULL,
    ip_address character varying(45),
    user_agent text,
    expires_at timestamp without time zone NOT NULL,
    revoked_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    previous_refresh_token_hash character varying(255),
    refresh_grace_until timestamp without time zone,
    refresh_claims jsonb,
    last_used_at timestamp without time zone
);


--
-- Name: auth_sessions_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.auth_sessions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.auth_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: department_permissions; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.department_permissions (
    id bigint NOT NULL,
    permission_id bigint NOT NULL,
    department_id bigint NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: department_permissions_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.department_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME iam.department_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.departments (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    name_th character varying(100) NOT NULL,
    name_en character varying(100) NOT NULL,
    description text,
    is_active boolean DEFAULT true,
    created_by bigint,
    updated_by bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.departments ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menus; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.menus (
    id bigint NOT NULL,
    parent_id bigint,
    code character varying(50) NOT NULL,
    name_th character varying(100) NOT NULL,
    name_en character varying(100) NOT NULL,
    menu_type character varying(10) DEFAULT 'MAIN'::character varying,
    path character varying(255),
    icon character varying(50),
    sort_order integer DEFAULT 0,
    is_visible boolean DEFAULT true,
    is_active boolean DEFAULT true,
    created_by bigint,
    updated_by bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT menus_menu_type_check CHECK (((menu_type)::text = ANY ((ARRAY['MAIN'::character varying, 'SUB'::character varying])::text[])))
);


--
-- Name: menus_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.menus ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.menus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: migrations; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.migrations (
    id integer NOT NULL,
    "timestamp" bigint NOT NULL,
    name character varying NOT NULL
);


--
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

CREATE SEQUENCE iam.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: iam; Owner: -
--

ALTER SEQUENCE iam.migrations_id_seq OWNED BY iam.migrations.id;


--
-- Name: permissions; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.permissions (
    id bigint NOT NULL,
    menu_id bigint NOT NULL,
    action_id bigint NOT NULL,
    code character varying(100) NOT NULL,
    description text,
    is_active boolean DEFAULT true,
    created_by bigint,
    updated_by bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.permissions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_actions; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.role_actions (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    action_id bigint NOT NULL,
    is_active boolean DEFAULT true,
    created_by bigint,
    updated_by bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: role_actions_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.role_actions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.role_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.roles (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name_th character varying(100) NOT NULL,
    name_en character varying(100) NOT NULL,
    scope_type character varying(20) DEFAULT 'DEPARTMENT'::character varying,
    description text,
    is_system boolean DEFAULT false,
    is_active boolean DEFAULT true,
    created_by bigint,
    updated_by bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT roles_scope_type_check CHECK (((scope_type)::text = ANY ((ARRAY['SYSTEM'::character varying, 'DEPARTMENT'::character varying])::text[])))
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.roles ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_department_permissions; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.user_department_permissions (
    id bigint NOT NULL,
    user_department_role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    is_active boolean DEFAULT true,
    granted_at timestamp without time zone,
    granted_by bigint,
    expires_at timestamp without time zone,
    created_by bigint,
    updated_by bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    effect character varying(10) DEFAULT 'ALLOW'::character varying NOT NULL,
    CONSTRAINT user_department_permissions_effect_check CHECK (((effect)::text = ANY ((ARRAY['ALLOW'::character varying, 'DENY'::character varying])::text[])))
);


--
-- Name: user_department_permissions_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.user_department_permissions ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.user_department_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_department_roles; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.user_department_roles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    department_id bigint,
    role_id bigint NOT NULL,
    is_active boolean DEFAULT true,
    assigned_at timestamp without time zone,
    assigned_by bigint,
    expired_at timestamp without time zone,
    created_by bigint,
    updated_by bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: user_department_roles_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.user_department_roles ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.user_department_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: iam; Owner: -
--

CREATE TABLE iam.users (
    id bigint NOT NULL,
    username character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(255),
    telephone character varying(20),
    is_active boolean DEFAULT true,
    is_locked boolean DEFAULT false,
    failed_login_attempts integer DEFAULT 0,
    locked_until timestamp without time zone,
    last_login_at timestamp without time zone,
    permission_version integer DEFAULT 1,
    created_by bigint,
    updated_by bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: iam; Owner: -
--

ALTER TABLE iam.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME iam.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: migrations id; Type: DEFAULT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.migrations ALTER COLUMN id SET DEFAULT nextval('iam.migrations_id_seq'::regclass);


--
-- Data for Name: actions; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.actions (id, code, name_th, name_en, description, sort_order, is_system, is_active, created_by, updated_by, created_at, updated_at) FROM stdin;
1	POST	รับรองเอกสาร	Post	\N	5	t	t	\N	\N	2026-09-15 22:07:59.519098	2026-09-15 22:07:59.519098
2	CANCEL	ยกเลิกเอกสาร	Cancel	\N	6	t	t	\N	\N	2026-09-15 22:07:59.519098	2026-09-15 22:07:59.519098
3	CREATE	สร้าง	Create	\N	1	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
4	READ	อ่าน	Read	\N	2	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
5	UPDATE	แก้ไข	Update	\N	3	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
6	DELETE	ลบ	Delete	\N	4	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
7	APPROVE	อนุมัติ	Approve	\N	7	t	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
8	ISSUE	ตัดจ่าย	Issue	\N	8	t	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
9	PRINT	พิมพ์	Print	\N	9	t	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
10	PICK	หยิบสินค้า	Pick	\N	10	t	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
\.


--
-- Data for Name: department_permissions; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.department_permissions (id, permission_id, department_id, is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: departments; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.departments (id, code, name_th, name_en, description, is_active, created_by, updated_by, created_at, updated_at) FROM stdin;
1	WE	แผนก WE	WE Department	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
2	PS	แผนก PS	PS Department	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
\.


--
-- Data for Name: menus; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.menus (id, parent_id, code, name_th, name_en, menu_type, path, icon, sort_order, is_visible, is_active, created_by, updated_by, created_at, updated_at) FROM stdin;
12	27	UNIT_MANAGEMENT	จัดการหน่วยนับ	Unit Management	SUB	/master-data/units	ruler	0	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:02.207603
13	27	SUPPLIER_MANAGEMENT	จัดการผู้จัดจำหน่าย	Supplier Management	SUB	/master-data/suppliers	truck	1	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:02.207603
14	27	MATERIAL_MODEL_MANAGEMENT	จัดการรุ่นวัสดุ	Material Model Management	SUB	/master-data/material-models	box	2	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:02.207603
5	\N	MENU_MANAGEMENT	จัดการเมนู	Menu Management	MAIN	/menus	menu	2	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:33.530313
15	27	DELIVERY_TYPE_MANAGEMENT	จัดการประเภทการจัดส่ง	Delivery Type Management	SUB	/master-data/delivery-types	truck	3	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:02.207603
16	27	LOADING_POINT_MANAGEMENT	จัดการจุดขนถ่าย	Loading Point Management	SUB	/master-data/loading-points	map-pin	4	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:02.207603
8	\N	AUDIT_LOG	บันทึกการใช้งาน	Audit Log	MAIN	/audit-logs	file-text	6	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:02.207603
9	\N	MATERIALS_MANAGEMENTS	จัดการวัสดุ	Materials Management	MAIN	/materials	box	3	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:19.663719
20	9	MATERIALS_RECEIVING	รับเข้าวัตถุดิบ	Materials Receiving	SUB	/materials/materials-receiving	package-plus	1	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:23:51.233702
21	9	MATERIALS_DISBURSEMENT	จ่ายออกวัสดุ	Materials Disbursement	SUB	/materials/materials-disbursement	scissors	2	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:23:51.233702
24	9	MATERIALS_REPORT	รายงานวัสดุคงคลัง	Materials Stock Report	SUB	/materials/materials-report	file-bar-chart	3	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:23:51.233702
10	\N	PRODUCTS_LIST	ชิ้นส่วนยานยนต์	Automotive Parts	MAIN	/products	car	4	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-22 05:59:55.646573
11	10	BOMS	สูตรการประกอบ (BOM)	Bill of Materials	SUB	/products	git-branch	0	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:23:51.233702
1	\N	DASHBOARD	แดชบอร์ด	Dashboard	MAIN	/dashboard	layout-dashboard	0	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:23:51.233702
26	\N	ACCESS CONTROL	Access Control	Access Control	MAIN		shield-check	1	t	t	\N	\N	2026-09-15 23:22:49.988306	2026-09-15 23:26:33.530313
2	26	USER_MANAGEMENT	จัดการผู้ใช้งาน	User Management	SUB	/users	users	2	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:23:51.233702
3	26	DEPARTMENT_MANAGEMENT	จัดการแผนก	Department Management	SUB	/departments	building	4	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:23:51.233702
4	26	ROLE_MANAGEMENT	จัดการบทบาท	Role Management	SUB	/roles	shield	3	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:23:51.233702
6	26	PERMISSION_MANAGEMENT	จัดการสิทธิ์	Permission Management	SUB	/permissions	key	1	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:23:51.233702
7	26	SESSION_MANAGEMENT	จัดการเซสชัน	Session Management	SUB	/sessions	clock	0	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:23:51.233702
34	27	CUSTOMER_MANAGEMENT	จัดการลูกค้า	Customer Management	SUB	/master-data/customers	users	12	t	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
35	27	LOCATION_MANAGEMENT	จัดการสถานที่	Location Management	SUB	/master-data/locations	map-pin	13	t	t	\N	\N	2026-09-21 08:08:48.789989	2026-09-21 08:08:48.789989
36	27	PROCESS_LINE_MANAGEMENT	จัดการสายการผลิต	Process Line Management	SUB	/master-data/process-lines	git-branch	14	t	t	\N	\N	2026-09-21 08:08:48.789989	2026-09-21 08:08:48.789989
27	\N	MASTER DATA	MAster Data	MAster Data	MAIN		folder-tree	5	t	t	\N	\N	2026-09-15 23:24:42.293788	2026-09-22 05:59:55.646573
37	\N	PRODUCTION_PLANS	แผนการผลิต	Production Plans	MAIN	/production/plans	clipboard-list	97	t	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
38	9	MATERIAL_JOB_ORDERS	ใบจัดงาน	Job Orders	SUB	/materials/job-orders	clipboard-check	4	t	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
17	27	CATEGORY_MANAGEMENT	จัดการหมวดหมู่	Category Management	SUB	/master-data/categories	folder-tree	5	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:02.207603
18	27	STATUS_ITEM_MANAGEMENT	จัดการสถานะ	Status Item Management	SUB	/master-data/statuses	tag	6	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:02.207603
19	27	ORGANIZATION_MANAGEMENT	จัดการองค์กร	Organization Management	SUB	/master-data/organizations	building	7	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:02.207603
25	27	REJECT_REASON_MANAGEMENT	จัดการเหตุผลการปฏิเสธ	Reject Reason Management	SUB	/master-data/reject-reasons	x-circle	8	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 23:26:02.207603
30	27	MATERIAL_TYPE_MANAGEMENT	จัดการประเภทวัสดุ	Material Type Management	SUB	/master-data/material-types	tag	9	t	t	\N	\N	2026-09-16 00:44:42.138946	2026-09-16 00:44:42.138946
31	9	MATERIALS_PC_OVERVIEW	ภาพรวมวัตถุดิบ	Materials Overview	SUB	/materials/pc	gauge	0	t	t	\N	\N	2026-09-19 22:44:22.375922	2026-09-19 22:44:22.375922
32	27	PRODUCT_TYPE_MANAGEMENT	จัดการประเภทสินค้า	Product Type Management	SUB	/master-data/product-types	tag	10	t	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
33	27	PRODUCT_MODEL_MANAGEMENT	จัดการรุ่นสินค้า	Product Model Management	SUB	/master-data/product-models	car	11	t	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
\.


--
-- Data for Name: migrations; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.migrations (id, "timestamp", name) FROM stdin;
1	1700000000000	CreateIamSchema1700000000000
2	1700000000001	CreateIamTables1700000000001
3	1700000000002	AddPermissionEffect1700000000002
4	1700000000003	CreateDepartmentPermissions1700000000003
5	1700000000004	AddUserAssignmentUniqueness1700000000004
6	1700000000005	CreateMaterialMaster1700000000005
7	1700000000006	AddMaterialCodeCaseInsensitiveIndex1700000000006
8	1700000000007	CreateAdditionalMasterTables1700000000007
9	1700000000009	AddPostCancelActions1700000000009
10	1786197666075	AddTypeToMaterial1786197666075
11	1786197666076	CreateMaterialsReceiving1786197666076
12	1786197666077	AddRunNoAndPackageTracking1786197666077
13	1786197666078	AddLotDetailNo1786197666078
14	1786197666079	FixConfirmedFieldsCheckConstraint1786197666079
15	1786700000000	AddMaterialShapeAndRatioToMaterial1786700000000
16	1786700000001	AddPoNoAndMaterialSnapshotToReceiving1786700000001
17	1786700000002	AddPiecesQrToReceiving1786700000002
18	1786700000003	CreateMaterialsDisbursement1786700000003
19	1786700000004	CreateProductsAndBoms1786700000004
20	1786700000005	RebuildProductsAndAddMasters1786700000005
21	1786700000006	CreateProductWorkflows1786700000006
22	1786700000007	AddProcessStepsMaster1786700000007
23	1786700000008	AddMaterialLotCounterAndPackageRemainingQty1786700000008
24	1786700000009	AddMaterialMinimumStock1786700000009
25	1786700000010	RestoreMaterialPackingQuantityAndRejectReasons1786700000010
26	1786700000011	CreateMaterialTypesMaster1786700000011
27	1786700000012	AddMaterialTypeIdToMaterials1786700000012
28	1786700000013	AddMaterialsPcOverviewMenu1786700000013
29	1789800000000	AddRefreshRotation1789800000000
30	1786700000014	ReorderMaterialsPcOverviewMenu1786700000014
31	1789900000000	AllowDisbursementRefTypeOnStockTransactions1789900000000
32	1790000000000	AddMaterialTraceabilityLedger1790000000000
33	1790100000000	AddAuditColumnsToProductMasters1790100000000
34	1790100000001	AddProductMasterMenusAndPermissions1790100000001
35	1790200000000	AddAuditColumnsToLocationAndProcessLine1790200000000
36	1790200000001	AddLocationAndProcessLineMenusAndPermissions1790200000001
37	1790300000000	CreateProductionPlans1790300000000
38	1790300000001	AddProductionPlanMenuAndPermissions1790300000001
39	1790400000000	CreateMaterialJobOrders1790400000000
40	1790400000001	AddMaterialJobOrderMenuAndPermissions1790400000001
\.


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.permissions (id, menu_id, action_id, code, description, is_active, created_by, updated_by, created_at, updated_at) FROM stdin;
1	1	3	DASHBOARD_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
2	1	4	DASHBOARD_READ	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
3	1	5	DASHBOARD_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
4	1	6	DASHBOARD_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
5	2	3	USER_MANAGEMENT_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
6	2	4	USER_MANAGEMENT_READ	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
7	2	5	USER_MANAGEMENT_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
8	2	6	USER_MANAGEMENT_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
9	3	3	DEPARTMENT_MANAGEMENT_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
10	3	4	DEPARTMENT_MANAGEMENT_READ	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
11	3	5	DEPARTMENT_MANAGEMENT_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
12	3	6	DEPARTMENT_MANAGEMENT_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
13	4	3	ROLE_MANAGEMENT_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
14	4	4	ROLE_MANAGEMENT_READ	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
15	4	5	ROLE_MANAGEMENT_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
16	4	6	ROLE_MANAGEMENT_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
17	5	3	MENU_MANAGEMENT_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
18	5	4	MENU_MANAGEMENT_READ	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
19	5	5	MENU_MANAGEMENT_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
20	5	6	MENU_MANAGEMENT_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
21	6	3	PERMISSION_MANAGEMENT_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
22	6	4	PERMISSION_MANAGEMENT_READ	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
23	6	5	PERMISSION_MANAGEMENT_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
24	6	6	PERMISSION_MANAGEMENT_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
25	7	3	SESSION_MANAGEMENT_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
26	7	4	SESSION_MANAGEMENT_READ	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
27	7	5	SESSION_MANAGEMENT_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
28	7	6	SESSION_MANAGEMENT_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
29	8	3	AUDIT_LOG_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
30	8	4	AUDIT_LOG_READ	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
31	8	5	AUDIT_LOG_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
32	8	6	AUDIT_LOG_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
33	9	3	MATERIAL_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
34	9	4	MATERIAL_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
35	9	5	MATERIAL_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
36	9	6	MATERIAL_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
37	10	3	PRODUCTS_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
38	10	4	PRODUCTS_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
39	10	5	PRODUCTS_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
40	10	6	PRODUCTS_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
41	11	3	BOMS_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
42	11	4	BOMS_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
43	11	5	BOMS_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
44	11	6	BOMS_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
45	12	3	UNIT_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
46	12	4	UNIT_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
47	12	5	UNIT_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
48	12	6	UNIT_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
49	13	3	SUPPLIER_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
50	13	4	SUPPLIER_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
51	13	5	SUPPLIER_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
52	13	6	SUPPLIER_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
53	14	3	MATERIAL_MODEL_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
54	14	4	MATERIAL_MODEL_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
55	14	5	MATERIAL_MODEL_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
56	14	6	MATERIAL_MODEL_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
57	15	3	DELIVERY_TYPE_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
58	15	4	DELIVERY_TYPE_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
59	15	5	DELIVERY_TYPE_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
60	15	6	DELIVERY_TYPE_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
61	16	3	LOADING_POINT_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
62	16	4	LOADING_POINT_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
63	16	5	LOADING_POINT_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
64	16	6	LOADING_POINT_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
65	17	3	CATEGORY_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
66	17	4	CATEGORY_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
67	17	5	CATEGORY_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
68	17	6	CATEGORY_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
69	18	3	STATUS_ITEM_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
70	18	4	STATUS_ITEM_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
71	18	5	STATUS_ITEM_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
72	18	6	STATUS_ITEM_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
73	19	3	ORGANIZATION_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
74	19	4	ORGANIZATION_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
75	19	5	ORGANIZATION_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
76	19	6	ORGANIZATION_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
77	20	3	MATERIALS_RECEIVING_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
78	20	4	MATERIALS_RECEIVING_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
79	20	5	MATERIALS_RECEIVING_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
80	20	6	MATERIALS_RECEIVING_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
81	20	1	MATERIALS_RECEIVING_CONFIRM	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
82	20	2	MATERIALS_RECEIVING_CANCEL	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
83	21	3	MATERIALS_DISBURSEMENT_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
84	21	4	MATERIALS_DISBURSEMENT_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
85	21	5	MATERIALS_DISBURSEMENT_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
86	21	6	MATERIALS_DISBURSEMENT_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
87	21	1	MATERIALS_DISBURSEMENT_CONFIRM	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
88	21	2	MATERIALS_DISBURSEMENT_CANCEL	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
89	25	3	REJECT_REASON_CREATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
90	25	4	REJECT_REASON_VIEW	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
91	25	5	REJECT_REASON_UPDATE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
92	25	6	REJECT_REASON_DELETE	\N	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
93	30	3	MATERIAL_TYPE_CREATE	\N	t	\N	\N	2026-09-16 00:44:42.138946	2026-09-16 00:44:42.138946
94	30	4	MATERIAL_TYPE_VIEW	\N	t	\N	\N	2026-09-16 00:44:42.138946	2026-09-16 00:44:42.138946
95	30	5	MATERIAL_TYPE_UPDATE	\N	t	\N	\N	2026-09-16 00:44:42.138946	2026-09-16 00:44:42.138946
96	30	6	MATERIAL_TYPE_DELETE	\N	t	\N	\N	2026-09-16 00:44:42.138946	2026-09-16 00:44:42.138946
97	32	4	PRODUCT_TYPE_VIEW	จัดการประเภทสินค้า — VIEW	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
98	32	3	PRODUCT_TYPE_CREATE	จัดการประเภทสินค้า — CREATE	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
99	32	5	PRODUCT_TYPE_UPDATE	จัดการประเภทสินค้า — UPDATE	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
100	32	6	PRODUCT_TYPE_DELETE	จัดการประเภทสินค้า — DELETE	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
101	33	4	PRODUCT_MODEL_VIEW	จัดการรุ่นสินค้า — VIEW	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
102	33	3	PRODUCT_MODEL_CREATE	จัดการรุ่นสินค้า — CREATE	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
103	33	5	PRODUCT_MODEL_UPDATE	จัดการรุ่นสินค้า — UPDATE	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
104	33	6	PRODUCT_MODEL_DELETE	จัดการรุ่นสินค้า — DELETE	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
105	34	4	CUSTOMER_VIEW	จัดการลูกค้า — VIEW	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
106	34	3	CUSTOMER_CREATE	จัดการลูกค้า — CREATE	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
107	34	5	CUSTOMER_UPDATE	จัดการลูกค้า — UPDATE	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
108	34	6	CUSTOMER_DELETE	จัดการลูกค้า — DELETE	t	\N	\N	2026-09-21 00:05:09.557801	2026-09-21 00:05:09.557801
109	35	4	LOCATION_VIEW	จัดการสถานที่ — VIEW	t	\N	\N	2026-09-21 08:08:48.789989	2026-09-21 08:08:48.789989
110	35	3	LOCATION_CREATE	จัดการสถานที่ — CREATE	t	\N	\N	2026-09-21 08:08:48.789989	2026-09-21 08:08:48.789989
111	35	5	LOCATION_UPDATE	จัดการสถานที่ — UPDATE	t	\N	\N	2026-09-21 08:08:48.789989	2026-09-21 08:08:48.789989
112	35	6	LOCATION_DELETE	จัดการสถานที่ — DELETE	t	\N	\N	2026-09-21 08:08:48.789989	2026-09-21 08:08:48.789989
113	36	4	PROCESS_LINE_VIEW	จัดการสายการผลิต — VIEW	t	\N	\N	2026-09-21 08:08:48.789989	2026-09-21 08:08:48.789989
114	36	3	PROCESS_LINE_CREATE	จัดการสายการผลิต — CREATE	t	\N	\N	2026-09-21 08:08:48.789989	2026-09-21 08:08:48.789989
115	36	5	PROCESS_LINE_UPDATE	จัดการสายการผลิต — UPDATE	t	\N	\N	2026-09-21 08:08:48.789989	2026-09-21 08:08:48.789989
116	36	6	PROCESS_LINE_DELETE	จัดการสายการผลิต — DELETE	t	\N	\N	2026-09-21 08:08:48.789989	2026-09-21 08:08:48.789989
117	37	4	PRODUCTION_PLAN_VIEW	แผนการผลิต — READ	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
118	37	3	PRODUCTION_PLAN_CREATE	แผนการผลิต — CREATE	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
119	37	5	PRODUCTION_PLAN_UPDATE	แผนการผลิต — UPDATE	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
120	37	6	PRODUCTION_PLAN_DELETE	แผนการผลิต — DELETE	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
121	37	7	PRODUCTION_PLAN_APPROVE	แผนการผลิต — APPROVE	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
122	37	8	PRODUCTION_PLAN_ISSUE	แผนการผลิต — ISSUE	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
123	37	2	PRODUCTION_PLAN_CANCEL	แผนการผลิต — CANCEL	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
124	38	4	MATERIAL_JOB_ORDER_VIEW	ใบจัดงาน — READ	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
125	38	9	MATERIAL_JOB_ORDER_PRINT	ใบจัดงาน — PRINT	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
126	38	10	MATERIAL_JOB_ORDER_PICK	ใบจัดงาน — PICK	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
127	38	8	MATERIAL_JOB_ORDER_ISSUE	ใบจัดงาน — ISSUE	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
\.


--
-- Data for Name: role_actions; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.role_actions (id, role_id, action_id, is_active, created_by, updated_by, created_at, updated_at) FROM stdin;
1	1	3	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
2	1	4	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
3	1	5	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
4	1	6	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
5	1	1	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
6	1	2	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
7	2	3	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
8	2	4	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
9	2	5	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
10	2	6	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
11	2	1	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
12	2	2	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
13	3	3	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
14	3	4	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
15	3	5	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
16	1	7	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
17	2	7	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
18	1	8	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
19	2	8	t	\N	\N	2026-09-22 22:49:57.195349	2026-09-22 22:49:57.195349
20	1	9	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
21	2	9	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
22	1	10	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
23	2	10	t	\N	\N	2026-09-23 08:21:27.727358	2026-09-23 08:21:27.727358
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.roles (id, code, name_th, name_en, scope_type, description, is_system, is_active, created_by, updated_by, created_at, updated_at) FROM stdin;
1	SUPER_ADMIN	ผู้ดูแลระบบสูงสุด	Super Admin	SYSTEM	\N	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
2	ADMIN	ผู้ดูแลระบบ	Admin	DEPARTMENT	\N	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
3	USER	ผู้ใช้งาน	User	DEPARTMENT	\N	t	t	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
\.


--
-- Data for Name: user_department_permissions; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.user_department_permissions (id, user_department_role_id, permission_id, is_active, granted_at, granted_by, expires_at, created_by, updated_by, created_at, updated_at, effect) FROM stdin;
\.


--
-- Data for Name: user_department_roles; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.user_department_roles (id, user_id, department_id, role_id, is_active, assigned_at, assigned_by, expired_at, created_by, updated_by, created_at, updated_at) FROM stdin;
1	1	\N	1	t	2026-09-15 22:10:49.057876	\N	\N	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
2	2	\N	1	t	2026-09-15 22:13:33.242145	\N	\N	\N	\N	2026-09-15 22:13:33.242145	2026-09-15 22:13:33.242145
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: iam; Owner: -
--

COPY iam.users (id, username, password_hash, first_name, last_name, email, telephone, is_active, is_locked, failed_login_attempts, locked_until, last_login_at, permission_version, created_by, updated_by, created_at, updated_at) FROM stdin;
1	superadmin	$argon2id$v=19$m=65536,t=3,p=4$RQBxzgjTbyqh4VICBat3LA$u9ScitUa0G+FUbocPmgZvfJvS++8ENX16kgKVe7wkKA	System	Administrator	superadmin@example.com	\N	t	f	0	\N	\N	1	\N	\N	2026-09-15 22:10:49.057876	2026-09-15 22:10:49.057876
2	cps-admin	$argon2id$v=19$m=65536,t=3,p=4$HfszN3A9ehxtk/fI1QU3hw$XfFfaQdD+oZVMhuiN9Nxew0IotflJ6P/RU/y/OhTyEQ	System	Administrator	cps-admin@example.com	\N	t	f	0	\N	2026-09-23 07:12:31.011	1	\N	\N	2026-09-15 22:13:33.242145	2026-09-23 14:12:31.015632
\.


--
-- Name: actions_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.actions_id_seq', 10, true);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.audit_logs_id_seq', 233, true);


--
-- Name: auth_sessions_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.auth_sessions_id_seq', 95, true);


--
-- Name: department_permissions_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.department_permissions_id_seq', 1, false);


--
-- Name: departments_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.departments_id_seq', 2, true);


--
-- Name: menus_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.menus_id_seq', 38, true);


--
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.migrations_id_seq', 40, true);


--
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.permissions_id_seq', 127, true);


--
-- Name: role_actions_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.role_actions_id_seq', 23, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.roles_id_seq', 6, true);


--
-- Name: user_department_permissions_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.user_department_permissions_id_seq', 2, true);


--
-- Name: user_department_roles_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.user_department_roles_id_seq', 7, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: iam; Owner: -
--

SELECT pg_catalog.setval('iam.users_id_seq', 7, true);


--
-- Name: migrations PK_8c82d7f526340ab734260ea46be; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.migrations
    ADD CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY (id);


--
-- Name: actions actions_code_key; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.actions
    ADD CONSTRAINT actions_code_key UNIQUE (code);


--
-- Name: actions actions_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.actions
    ADD CONSTRAINT actions_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: auth_sessions auth_sessions_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (id);


--
-- Name: department_permissions department_permissions_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.department_permissions
    ADD CONSTRAINT department_permissions_pkey PRIMARY KEY (id);


--
-- Name: departments departments_code_key; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.departments
    ADD CONSTRAINT departments_code_key UNIQUE (code);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: menus menus_code_key; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.menus
    ADD CONSTRAINT menus_code_key UNIQUE (code);


--
-- Name: menus menus_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.menus
    ADD CONSTRAINT menus_pkey PRIMARY KEY (id);


--
-- Name: permissions permissions_code_key; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.permissions
    ADD CONSTRAINT permissions_code_key UNIQUE (code);


--
-- Name: permissions permissions_menu_id_action_id_key; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.permissions
    ADD CONSTRAINT permissions_menu_id_action_id_key UNIQUE (menu_id, action_id);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: role_actions role_actions_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.role_actions
    ADD CONSTRAINT role_actions_pkey PRIMARY KEY (id);


--
-- Name: role_actions role_actions_role_id_action_id_key; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.role_actions
    ADD CONSTRAINT role_actions_role_id_action_id_key UNIQUE (role_id, action_id);


--
-- Name: roles roles_code_key; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.roles
    ADD CONSTRAINT roles_code_key UNIQUE (code);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: department_permissions uq_department_permissions_permission_department; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.department_permissions
    ADD CONSTRAINT uq_department_permissions_permission_department UNIQUE (permission_id, department_id);


--
-- Name: user_department_roles uq_user_department_roles_user_department_role; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.user_department_roles
    ADD CONSTRAINT uq_user_department_roles_user_department_role UNIQUE (user_id, department_id, role_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_department_permissions user_department_permissions_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.user_department_permissions
    ADD CONSTRAINT user_department_permissions_pkey PRIMARY KEY (id);


--
-- Name: user_department_roles user_department_roles_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.user_department_roles
    ADD CONSTRAINT user_department_roles_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: idx_audit_logs_action; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_audit_logs_action ON iam.audit_logs USING btree (action);


--
-- Name: idx_audit_logs_actor_user_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_audit_logs_actor_user_id ON iam.audit_logs USING btree (actor_user_id);


--
-- Name: idx_audit_logs_created_at; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_audit_logs_created_at ON iam.audit_logs USING btree (created_at);


--
-- Name: idx_audit_logs_department_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_audit_logs_department_id ON iam.audit_logs USING btree (department_id);


--
-- Name: idx_audit_logs_trace_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_audit_logs_trace_id ON iam.audit_logs USING btree (trace_id);


--
-- Name: idx_auth_sessions_active_user_department_role_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_auth_sessions_active_user_department_role_id ON iam.auth_sessions USING btree (active_user_department_role_id);


--
-- Name: idx_auth_sessions_user_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_auth_sessions_user_id ON iam.auth_sessions USING btree (user_id);


--
-- Name: idx_department_permissions_department_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_department_permissions_department_id ON iam.department_permissions USING btree (department_id);


--
-- Name: idx_department_permissions_permission_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_department_permissions_permission_id ON iam.department_permissions USING btree (permission_id);


--
-- Name: idx_user_department_permissions_permission_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_user_department_permissions_permission_id ON iam.user_department_permissions USING btree (permission_id);


--
-- Name: idx_user_department_permissions_user_department_role_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_user_department_permissions_user_department_role_id ON iam.user_department_permissions USING btree (user_department_role_id);


--
-- Name: idx_user_department_roles_department_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_user_department_roles_department_id ON iam.user_department_roles USING btree (department_id);


--
-- Name: idx_user_department_roles_role_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_user_department_roles_role_id ON iam.user_department_roles USING btree (role_id);


--
-- Name: idx_user_department_roles_user_id; Type: INDEX; Schema: iam; Owner: -
--

CREATE INDEX idx_user_department_roles_user_id ON iam.user_department_roles USING btree (user_id);


--
-- Name: uq_user_department_roles_user_system_role; Type: INDEX; Schema: iam; Owner: -
--

CREATE UNIQUE INDEX uq_user_department_roles_user_system_role ON iam.user_department_roles USING btree (user_id, role_id) WHERE (department_id IS NULL);


--
-- Name: audit_logs audit_logs_actor_user_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.audit_logs
    ADD CONSTRAINT audit_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES iam.users(id) ON DELETE SET NULL;


--
-- Name: audit_logs audit_logs_department_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.audit_logs
    ADD CONSTRAINT audit_logs_department_id_fkey FOREIGN KEY (department_id) REFERENCES iam.departments(id) ON DELETE SET NULL;


--
-- Name: auth_sessions auth_sessions_active_user_department_role_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.auth_sessions
    ADD CONSTRAINT auth_sessions_active_user_department_role_id_fkey FOREIGN KEY (active_user_department_role_id) REFERENCES iam.user_department_roles(id) ON DELETE CASCADE;


--
-- Name: auth_sessions auth_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.auth_sessions
    ADD CONSTRAINT auth_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES iam.users(id) ON DELETE CASCADE;


--
-- Name: department_permissions fk_department_permissions_department; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.department_permissions
    ADD CONSTRAINT fk_department_permissions_department FOREIGN KEY (department_id) REFERENCES iam.departments(id) ON DELETE CASCADE;


--
-- Name: department_permissions fk_department_permissions_permission; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.department_permissions
    ADD CONSTRAINT fk_department_permissions_permission FOREIGN KEY (permission_id) REFERENCES iam.permissions(id) ON DELETE CASCADE;


--
-- Name: menus menus_parent_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.menus
    ADD CONSTRAINT menus_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES iam.menus(id) ON DELETE CASCADE;


--
-- Name: permissions permissions_action_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.permissions
    ADD CONSTRAINT permissions_action_id_fkey FOREIGN KEY (action_id) REFERENCES iam.actions(id) ON DELETE CASCADE;


--
-- Name: permissions permissions_menu_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.permissions
    ADD CONSTRAINT permissions_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES iam.menus(id) ON DELETE CASCADE;


--
-- Name: role_actions role_actions_action_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.role_actions
    ADD CONSTRAINT role_actions_action_id_fkey FOREIGN KEY (action_id) REFERENCES iam.actions(id) ON DELETE CASCADE;


--
-- Name: role_actions role_actions_role_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.role_actions
    ADD CONSTRAINT role_actions_role_id_fkey FOREIGN KEY (role_id) REFERENCES iam.roles(id) ON DELETE CASCADE;


--
-- Name: user_department_permissions user_department_permissions_permission_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.user_department_permissions
    ADD CONSTRAINT user_department_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES iam.permissions(id) ON DELETE CASCADE;


--
-- Name: user_department_permissions user_department_permissions_user_department_role_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.user_department_permissions
    ADD CONSTRAINT user_department_permissions_user_department_role_id_fkey FOREIGN KEY (user_department_role_id) REFERENCES iam.user_department_roles(id) ON DELETE CASCADE;


--
-- Name: user_department_roles user_department_roles_department_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.user_department_roles
    ADD CONSTRAINT user_department_roles_department_id_fkey FOREIGN KEY (department_id) REFERENCES iam.departments(id) ON DELETE CASCADE;


--
-- Name: user_department_roles user_department_roles_role_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.user_department_roles
    ADD CONSTRAINT user_department_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES iam.roles(id) ON DELETE CASCADE;


--
-- Name: user_department_roles user_department_roles_user_id_fkey; Type: FK CONSTRAINT; Schema: iam; Owner: -
--

ALTER TABLE ONLY iam.user_department_roles
    ADD CONSTRAINT user_department_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES iam.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 6jY4oxSyTm4hWK3iPtKbLJhZJdWcLyzhh7SuowyqDZA85b9NqpKs2DqyVe8eQkj

