#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"
ENV_FILE="$SCRIPT_DIR/.env"

banner "CPS local database setup"

stage "Check requirements"
say "This starts PostgreSQL 18 on localhost and imports the bundled backup."
step "Make sure Docker Desktop is installed and running."
if ! command -v docker >/dev/null 2>&1; then
  warn "Docker was not found. Install Docker Desktop, then run this wizard again."
  open_url "https://www.docker.com/products/docker-desktop/"
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  warn "Docker is installed but is not running. Start Docker Desktop, then retry."
  exit 1
fi
if [[ ! -s "$SCRIPT_DIR/init/001-structure.sql" || ! -s "$SCRIPT_DIR/init/002-iam-seed.sql" ]]; then
  warn "The SQL backup files are missing from the init folder."
  exit 1
fi
say "Docker and both SQL backup files are ready."
pause "Press Enter to configure the database."

stage "Database settings"
say "These values are stored only in backup/.env on this machine."
[[ -f "$ENV_FILE" ]] || touch "$ENV_FILE"
if ! _existing DB_PORT >/dev/null 2>&1; then write_env DB_PORT "5432"; fi
if ! _existing DB_USERNAME >/dev/null 2>&1; then write_env DB_USERNAME "postgres"; fi
if ! _existing DB_DATABASE >/dev/null 2>&1; then write_env DB_DATABASE "cps_database"; fi
ask DB_PORT "Local port (Enter keeps 5432):"
ask DB_USERNAME "Database username (Enter keeps postgres):"
ask DB_DATABASE "Database name (Enter keeps cps_database):"
ask_secret DB_PASSWORD "Database password (hidden):"
[[ "$DB_PORT" =~ ^[0-9]+$ ]] || { warn "Port must contain numbers only."; exit 1; }
[[ "$DB_USERNAME" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || { warn "Username contains unsupported characters."; exit 1; }
[[ "$DB_DATABASE" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || { warn "Database name contains unsupported characters."; exit 1; }
[[ -n "$DB_PASSWORD" ]] || { warn "Password cannot be empty."; exit 1; }
write_env DB_PORT "$DB_PORT"
write_env DB_USERNAME "$DB_USERNAME"
write_env DB_PASSWORD "$DB_PASSWORD"
write_env DB_DATABASE "$DB_DATABASE"
pause "Press Enter to review before starting PostgreSQL."

stage "Start and verify"
say "The first start imports all schema structures and IAM seed data."
warn "If this backup volume already exists, PostgreSQL will keep its existing data."
if ! confirm "Start the local database now?"; then
  say "Nothing was started. Re-run the wizard when ready."
  exit 0
fi
docker compose up -d
say "Waiting for PostgreSQL health check..."
ready=false
for _ in $(seq 1 40); do
  status=$(docker compose ps --format json 2>/dev/null || true)
  if [[ "$status" == *'"Health":"healthy"'* || "$status" == *'"Health": "healthy"'* ]]; then
    ready=true
    break
  fi
  sleep 2
done
if [[ "$ready" != true ]]; then
  warn "PostgreSQL did not become healthy in time. Check: docker compose logs postgres"
  exit 1
fi
docker compose exec -T postgres psql \
  --username "$DB_USERNAME" \
  --dbname "$DB_DATABASE" \
  --set ON_ERROR_STOP=1 \
  --command "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM iam.actions) OR NOT EXISTS (SELECT 1 FROM iam.menus) OR NOT EXISTS (SELECT 1 FROM iam.permissions) OR NOT EXISTS (SELECT 1 FROM iam.users) THEN RAISE EXCEPTION 'IAM seed verification failed'; END IF; IF EXISTS (SELECT 1 FROM master.materials) OR EXISTS (SELECT 1 FROM inventory.production_plans) THEN RAISE EXCEPTION 'Non-IAM schemas unexpectedly contain data'; END IF; END \$\$; SELECT table_schema, count(*) AS tables FROM information_schema.tables WHERE table_schema IN ('iam','master','inventory') AND table_type = 'BASE TABLE' GROUP BY table_schema ORDER BY table_schema;"
say "Database is ready at localhost:$DB_PORT/$DB_DATABASE"

finish
