export const GOODS_RECEIPT_PERMISSIONS = {
  VIEW: 'GOODS_RECEIPT_VIEW',
  CREATE: 'GOODS_RECEIPT_CREATE',
  UPDATE: 'GOODS_RECEIPT_UPDATE',
  DELETE: 'GOODS_RECEIPT_DELETE',
  POST: 'GOODS_RECEIPT_POST',
  CANCEL: 'GOODS_RECEIPT_CANCEL',
} as const;
