export const PRODUCTION_PLAN_PERMISSIONS = {
  VIEW: 'PRODUCTION_PLAN_VIEW',
  CREATE: 'PRODUCTION_PLAN_CREATE',
  UPDATE: 'PRODUCTION_PLAN_UPDATE',
  DELETE: 'PRODUCTION_PLAN_DELETE',
  APPROVE: 'PRODUCTION_PLAN_APPROVE',
  ISSUE: 'PRODUCTION_PLAN_ISSUE',
  CANCEL: 'PRODUCTION_PLAN_CANCEL',
} as const;
