export const PRODUCT_WORKFLOWS_PERMISSIONS = {
  VIEW: 'PRODUCT_WORKFLOWS_VIEW',
  CREATE: 'PRODUCT_WORKFLOWS_CREATE',
  UPDATE: 'PRODUCT_WORKFLOWS_UPDATE',
  DELETE: 'PRODUCT_WORKFLOWS_DELETE',
} as const;
