export const MATERIAL_JOB_ORDER_PERMISSIONS = {
  VIEW: 'MATERIAL_JOB_ORDER_VIEW',
  PRINT: 'MATERIAL_JOB_ORDER_PRINT',
  PICK: 'MATERIAL_JOB_ORDER_PICK',
  ISSUE: 'MATERIAL_JOB_ORDER_ISSUE',
} as const;
