export const MATERIALS_RECEIVING_PERMISSIONS = {
  VIEW: 'MATERIALS_RECEIVING_VIEW',
  CREATE: 'MATERIALS_RECEIVING_CREATE',
  UPDATE: 'MATERIALS_RECEIVING_UPDATE',
  DELETE: 'MATERIALS_RECEIVING_DELETE',
  CONFIRM: 'MATERIALS_RECEIVING_CONFIRM',
  CANCEL: 'MATERIALS_RECEIVING_CANCEL',
} as const;
