export const BOMS_PERMISSIONS = {
  VIEW: 'BOMS_VIEW',
  CREATE: 'BOMS_CREATE',
  UPDATE: 'BOMS_UPDATE',
  DELETE: 'BOMS_DELETE',
  ACTIVATE: 'BOMS_ACTIVATE',
  DEACTIVATE: 'BOMS_DEACTIVATE',
} as const;
